//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serko.Expense.ApplicationCore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Validators_ExpenseClaimInputValidator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validators_ExpenseClaimInputValidator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Serko.Expense.ApplicationCore.Resources.Validators.ExpenseClaimInputValidator", typeof(Validators_ExpenseClaimInputValidator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The closing tag &lt;{0}&gt; has no corresponding opening tag..
        /// </summary>
        internal static string ClosingTagXHasNoCorrespondingOpeningTags {
            get {
                return ResourceManager.GetString("ClosingTagXHasNoCorrespondingOpeningTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expense claim text should not be blank..
        /// </summary>
        internal static string ExpenseClaimTextNotBeBlank {
            get {
                return ResourceManager.GetString("ExpenseClaimTextNotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The opening tag &lt;{0}&gt; has no corresponding closing tag..
        /// </summary>
        internal static string OpeningTagXHasNoCorrespondingClosingTags {
            get {
                return ResourceManager.GetString("OpeningTagXHasNoCorrespondingClosingTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;total&gt; amount is not present in the expense claim text..
        /// </summary>
        internal static string TotalAmountNotPresentInExpenseClaimText {
            get {
                return ResourceManager.GetString("TotalAmountNotPresentInExpenseClaimText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount &apos;{0}&apos; specified by &lt;total&gt; should be a numeric value..
        /// </summary>
        internal static string TotalAmountShouldBeNumeric {
            get {
                return ResourceManager.GetString("TotalAmountShouldBeNumeric", resourceCulture);
            }
        }
    }
}
